// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job/Job.proto

package com.kptl.proto.job;

public interface FindJobByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *职位id
   * </pre>
   *
   * <code>int32 jobId = 1;</code>
   */
  int getJobId();

  /**
   * <pre>
   *用户id
   * </pre>
   *
   * <code>int32 id = 2;</code>
   */
  int getId();
}
