// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto.job;

public interface FindJobsByIndustryReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobsByIndustryReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string industry = 1;</code>
   */
  java.lang.String getIndustry();
  /**
   * <code>string industry = 1;</code>
   */
  com.google.protobuf.ByteString
      getIndustryBytes();

  /**
   * <code>int32 index = 2;</code>
   */
  int getIndex();

  /**
   * <code>int32 size = 3;</code>
   */
  int getSize();
}
