// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job/Job.proto

package com.kptl.proto.job;

public interface FindJobsByTypeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobsByTypeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   */
  int getIndex();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>int32 jobType = 3;</code>
   */
  int getJobType();
}
