// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto.job;

public interface FindJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.job.ResponseHeader getHeader();
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.job.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .job.JobMessage jobMsg = 2;</code>
   */
  java.util.List<com.kptl.proto.job.JobMessage> 
      getJobMsgList();
  /**
   * <code>repeated .job.JobMessage jobMsg = 2;</code>
   */
  com.kptl.proto.job.JobMessage getJobMsg(int index);
  /**
   * <code>repeated .job.JobMessage jobMsg = 2;</code>
   */
  int getJobMsgCount();
  /**
   * <code>repeated .job.JobMessage jobMsg = 2;</code>
   */
  java.util.List<? extends com.kptl.proto.job.JobMessageOrBuilder> 
      getJobMsgOrBuilderList();
  /**
   * <code>repeated .job.JobMessage jobMsg = 2;</code>
   */
  com.kptl.proto.job.JobMessageOrBuilder getJobMsgOrBuilder(
      int index);
}
