// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto.job;

public final class Job {
  private Job() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_FindJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_FindJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_FindJobByNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_FindJobByNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_FindJobByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_FindJobByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_FindJobsByIndustryReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_FindJobsByIndustryReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_FindAllJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_FindAllJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_FindJobsByTypeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_FindJobsByTypeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_FindJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_FindJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_FindSimplifyJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_FindSimplifyJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_SaveJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_SaveJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_ResponseHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_ResponseHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_CommonCompanyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_CommonCompanyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_CommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_CommonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_JobMoney_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_JobMoney_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_JobMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_JobMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jobService_JobSimplifyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jobService_JobSimplifyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tJob.proto\022\njobService\"U\n\016FindJobReques" +
      "t\022\n\n\002id\030\001 \001(\005\022\014\n\004role\030\002 \001(\005\022\014\n\004byId\030\003 \001(" +
      "\005\022\r\n\005index\030\004 \001(\005\022\014\n\004size\030\005 \001(\005\"D\n\024FindJo" +
      "bByNameRequest\022\017\n\007jobName\030\001 \001(\t\022\r\n\005index" +
      "\030\002 \001(\005\022\014\n\004size\030\003 \001(\005\"/\n\022FindJobByIdReque" +
      "st\022\r\n\005jobId\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\"F\n\025FindJob" +
      "sByIndustryReq\022\020\n\010industry\030\001 \001(\t\022\r\n\005inde" +
      "x\030\002 \001(\005\022\014\n\004size\030\003 \001(\005\"0\n\021FindAllJobReque" +
      "st\022\r\n\005index\030\001 \001(\005\022\014\n\004size\030\002 \001(\005\"A\n\021FindJ" +
      "obsByTypeReq\022\r\n\005index\030\001 \001(\005\022\014\n\004size\030\002 \001(" +
      "\005\022\017\n\007jobType\030\003 \001(\005\"e\n\017FindJobResponse\022*\n" +
      "\006header\030\001 \001(\0132\032.jobService.ResponseHeade" +
      "r\022&\n\006jobMsg\030\002 \003(\0132\026.jobService.JobMessag" +
      "e\"u\n\027FindSimplifyJobResponse\022*\n\006header\030\001" +
      " \001(\0132\032.jobService.ResponseHeader\022.\n\006jobM" +
      "sg\030\002 \003(\0132\036.jobService.JobSimplifyMessage" +
      "\"=\n\017SaveJobResponse\022*\n\006header\030\001 \001(\0132\032.jo" +
      "bService.ResponseHeader\"M\n\016ResponseHeade" +
      "r\022*\n\006status\030\001 \001(\0162\032.jobService.ResponseS" +
      "tatus\022\017\n\007message\030\002 \001(\t\"\036\n\020CommonCompanyR" +
      "eq\022\n\n\002id\030\001 \001(\005\"<\n\016CommonResponse\022*\n\006head" +
      "er\030\001 \001(\0132\032.jobService.ResponseHeader\"M\n\010" +
      "JobMoney\022&\n\004type\030\001 \001(\0162\030.jobService.JobM" +
      "oneyType\022\013\n\003low\030\002 \001(\005\022\014\n\004high\030\003 \001(\005\"\313\001\n\n" +
      "JobMessage\0222\n\njobBaseMsg\030\001 \001(\0132\036.jobServ" +
      "ice.JobSimplifyMessage\022\016\n\006jobReq\030\002 \001(\t\022\017" +
      "\n\007jobNeed\030\003 \001(\005\022\020\n\010industry\030\005 \001(\t\022\025\n\rrec" +
      "ruiterName\030\006 \001(\t\022\026\n\016recruiterPhone\030\007 \001(\t" +
      "\022\023\n\013recruiterId\030\010 \001(\005\022\022\n\nupdateTime\030\t \001(" +
      "\003\"\342\001\n\022JobSimplifyMessage\022\r\n\005jobId\030\001 \001(\005\022" +
      "\017\n\007jobName\030\002 \001(\t\022\023\n\013jobLocation\030\003 \001(\t\022\023\n" +
      "\013companyName\030\004 \001(\t\022\017\n\007jobTags\030\005 \001(\t\022\021\n\tc" +
      "ompanyId\030\006 \001(\005\022\020\n\010openTime\030\007 \001(\003\022&\n\010jobM" +
      "oney\030\010 \001(\0132\024.jobService.JobMoney\022$\n\007jobT" +
      "ype\030\t \001(\0162\023.jobService.JobType*=\n\014JobMon" +
      "eyType\022\007\n\003F2F\020\000\022\007\n\003DAY\020\001\022\007\n\003MON\020\002\022\010\n\004TIM" +
      "E\020\003\022\010\n\004HOUR\020\004*/\n\007JobType\022\010\n\004LONG\020\000\022\t\n\005SH" +
      "ORT\020\001\022\017\n\013PARTTIMEJOB\020\002*)\n\016ResponseStatus" +
      "\022\006\n\002OK\020\000\022\017\n\013InternalErr\020\0012\320\005\n\nJobService" +
      "\022K\n\013FindAllJobs\022\035.jobService.FindAllJobR" +
      "equest\032\033.jobService.FindJobResponse\"\000\022P\n" +
      "\rFindJobByName\022 .jobService.FindJobByNam" +
      "eRequest\032\033.jobService.FindJobResponse\"\000\022" +
      "L\n\013FindJobById\022\036.jobService.FindJobByIdR" +
      "equest\032\033.jobService.FindJobResponse\"\000\022V\n" +
      "\022FindJobsByIndustry\022!.jobService.FindJob" +
      "sByIndustryReq\032\033.jobService.FindJobRespo" +
      "nse\"\000\022E\n\010FindJobs\022\032.jobService.FindJobRe" +
      "quest\032\033.jobService.FindJobResponse\"\000\022V\n\016" +
      "FindJobsByType\022\035.jobService.FindJobsByTy" +
      "peReq\032#.jobService.FindSimplifyJobRespon" +
      "se\"\000\022A\n\010SaveJobs\022\026.jobService.JobMessage" +
      "\032\033.jobService.SaveJobResponse\"\000\022V\n\020FindJ" +
      "obsSimplify\022\035.jobService.FindAllJobReque" +
      "st\032#.jobService.FindSimplifyJobResponse\022" +
      "C\n\nUpdateJobs\022\026.jobService.JobMessage\032\033." +
      "jobService.SaveJobResponse\"\000B\035\n\022com.kptl" +
      ".proto.jobP\001Z\005./jobb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_jobService_FindJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jobService_FindJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_FindJobRequest_descriptor,
        new java.lang.String[] { "Id", "Role", "ById", "Index", "Size", });
    internal_static_jobService_FindJobByNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jobService_FindJobByNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_FindJobByNameRequest_descriptor,
        new java.lang.String[] { "JobName", "Index", "Size", });
    internal_static_jobService_FindJobByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_jobService_FindJobByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_FindJobByIdRequest_descriptor,
        new java.lang.String[] { "JobId", "Id", });
    internal_static_jobService_FindJobsByIndustryReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_jobService_FindJobsByIndustryReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_FindJobsByIndustryReq_descriptor,
        new java.lang.String[] { "Industry", "Index", "Size", });
    internal_static_jobService_FindAllJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_jobService_FindAllJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_FindAllJobRequest_descriptor,
        new java.lang.String[] { "Index", "Size", });
    internal_static_jobService_FindJobsByTypeReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_jobService_FindJobsByTypeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_FindJobsByTypeReq_descriptor,
        new java.lang.String[] { "Index", "Size", "JobType", });
    internal_static_jobService_FindJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_jobService_FindJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_FindJobResponse_descriptor,
        new java.lang.String[] { "Header", "JobMsg", });
    internal_static_jobService_FindSimplifyJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_jobService_FindSimplifyJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_FindSimplifyJobResponse_descriptor,
        new java.lang.String[] { "Header", "JobMsg", });
    internal_static_jobService_SaveJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_jobService_SaveJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_SaveJobResponse_descriptor,
        new java.lang.String[] { "Header", });
    internal_static_jobService_ResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_jobService_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_ResponseHeader_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_jobService_CommonCompanyReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_jobService_CommonCompanyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_CommonCompanyReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_jobService_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_jobService_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_CommonResponse_descriptor,
        new java.lang.String[] { "Header", });
    internal_static_jobService_JobMoney_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_jobService_JobMoney_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_JobMoney_descriptor,
        new java.lang.String[] { "Type", "Low", "High", });
    internal_static_jobService_JobMessage_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_jobService_JobMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_JobMessage_descriptor,
        new java.lang.String[] { "JobBaseMsg", "JobReq", "JobNeed", "Industry", "RecruiterName", "RecruiterPhone", "RecruiterId", "UpdateTime", });
    internal_static_jobService_JobSimplifyMessage_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_jobService_JobSimplifyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jobService_JobSimplifyMessage_descriptor,
        new java.lang.String[] { "JobId", "JobName", "JobLocation", "CompanyName", "JobTags", "CompanyId", "OpenTime", "JobMoney", "JobType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
