// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job/Job.proto

package com.kptl.proto.job;

/**
 * Protobuf type {@code job.JobMoney}
 */
public  final class JobMoney extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:job.JobMoney)
    JobMoneyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobMoney.newBuilder() to construct.
  private JobMoney(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobMoney() {
    type_ = 0;
    low_ = 0;
    high_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobMoney(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 16: {

            low_ = input.readInt32();
            break;
          }
          case 24: {

            high_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kptl.proto.job.JobOuterClass.internal_static_job_JobMoney_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kptl.proto.job.JobOuterClass.internal_static_job_JobMoney_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kptl.proto.job.JobMoney.class, com.kptl.proto.job.JobMoney.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.job.JobMoneyType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.job.JobMoneyType type = 1;</code>
   */
  public com.kptl.proto.job.JobMoneyType getType() {
    com.kptl.proto.job.JobMoneyType result = com.kptl.proto.job.JobMoneyType.valueOf(type_);
    return result == null ? com.kptl.proto.job.JobMoneyType.UNRECOGNIZED : result;
  }

  public static final int LOW_FIELD_NUMBER = 2;
  private int low_;
  /**
   * <code>int32 low = 2;</code>
   */
  public int getLow() {
    return low_;
  }

  public static final int HIGH_FIELD_NUMBER = 3;
  private int high_;
  /**
   * <code>int32 high = 3;</code>
   */
  public int getHigh() {
    return high_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.kptl.proto.job.JobMoneyType.F2F.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (low_ != 0) {
      output.writeInt32(2, low_);
    }
    if (high_ != 0) {
      output.writeInt32(3, high_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.kptl.proto.job.JobMoneyType.F2F.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (low_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, low_);
    }
    if (high_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, high_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kptl.proto.job.JobMoney)) {
      return super.equals(obj);
    }
    com.kptl.proto.job.JobMoney other = (com.kptl.proto.job.JobMoney) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && (getLow()
        == other.getLow());
    result = result && (getHigh()
        == other.getHigh());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + LOW_FIELD_NUMBER;
    hash = (53 * hash) + getLow();
    hash = (37 * hash) + HIGH_FIELD_NUMBER;
    hash = (53 * hash) + getHigh();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kptl.proto.job.JobMoney parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kptl.proto.job.JobMoney parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kptl.proto.job.JobMoney parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kptl.proto.job.JobMoney parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kptl.proto.job.JobMoney prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code job.JobMoney}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:job.JobMoney)
      com.kptl.proto.job.JobMoneyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kptl.proto.job.JobOuterClass.internal_static_job_JobMoney_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kptl.proto.job.JobOuterClass.internal_static_job_JobMoney_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kptl.proto.job.JobMoney.class, com.kptl.proto.job.JobMoney.Builder.class);
    }

    // Construct using com.kptl.proto.job.JobMoney.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      low_ = 0;

      high_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kptl.proto.job.JobOuterClass.internal_static_job_JobMoney_descriptor;
    }

    public com.kptl.proto.job.JobMoney getDefaultInstanceForType() {
      return com.kptl.proto.job.JobMoney.getDefaultInstance();
    }

    public com.kptl.proto.job.JobMoney build() {
      com.kptl.proto.job.JobMoney result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.kptl.proto.job.JobMoney buildPartial() {
      com.kptl.proto.job.JobMoney result = new com.kptl.proto.job.JobMoney(this);
      result.type_ = type_;
      result.low_ = low_;
      result.high_ = high_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kptl.proto.job.JobMoney) {
        return mergeFrom((com.kptl.proto.job.JobMoney)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kptl.proto.job.JobMoney other) {
      if (other == com.kptl.proto.job.JobMoney.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getLow() != 0) {
        setLow(other.getLow());
      }
      if (other.getHigh() != 0) {
        setHigh(other.getHigh());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kptl.proto.job.JobMoney parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kptl.proto.job.JobMoney) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.job.JobMoneyType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.job.JobMoneyType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.job.JobMoneyType type = 1;</code>
     */
    public com.kptl.proto.job.JobMoneyType getType() {
      com.kptl.proto.job.JobMoneyType result = com.kptl.proto.job.JobMoneyType.valueOf(type_);
      return result == null ? com.kptl.proto.job.JobMoneyType.UNRECOGNIZED : result;
    }
    /**
     * <code>.job.JobMoneyType type = 1;</code>
     */
    public Builder setType(com.kptl.proto.job.JobMoneyType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.job.JobMoneyType type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int low_ ;
    /**
     * <code>int32 low = 2;</code>
     */
    public int getLow() {
      return low_;
    }
    /**
     * <code>int32 low = 2;</code>
     */
    public Builder setLow(int value) {
      
      low_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 low = 2;</code>
     */
    public Builder clearLow() {
      
      low_ = 0;
      onChanged();
      return this;
    }

    private int high_ ;
    /**
     * <code>int32 high = 3;</code>
     */
    public int getHigh() {
      return high_;
    }
    /**
     * <code>int32 high = 3;</code>
     */
    public Builder setHigh(int value) {
      
      high_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 high = 3;</code>
     */
    public Builder clearHigh() {
      
      high_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:job.JobMoney)
  }

  // @@protoc_insertion_point(class_scope:job.JobMoney)
  private static final com.kptl.proto.job.JobMoney DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kptl.proto.job.JobMoney();
  }

  public static com.kptl.proto.job.JobMoney getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobMoney>
      PARSER = new com.google.protobuf.AbstractParser<JobMoney>() {
    public JobMoney parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobMoney(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobMoney> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobMoney> getParserForType() {
    return PARSER;
  }

  public com.kptl.proto.job.JobMoney getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

