// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto.job;

/**
 * Protobuf enum {@code job.JobType}
 */
public enum JobType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *长工
   * </pre>
   *
   * <code>LONG = 0;</code>
   */
  LONG(0),
  /**
   * <pre>
   *短工
   * </pre>
   *
   * <code>SHORT = 1;</code>
   */
  SHORT(1),
  /**
   * <pre>
   *兼职
   * </pre>
   *
   * <code>PARTTIMEJOB = 2;</code>
   */
  PARTTIMEJOB(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *长工
   * </pre>
   *
   * <code>LONG = 0;</code>
   */
  public static final int LONG_VALUE = 0;
  /**
   * <pre>
   *短工
   * </pre>
   *
   * <code>SHORT = 1;</code>
   */
  public static final int SHORT_VALUE = 1;
  /**
   * <pre>
   *兼职
   * </pre>
   *
   * <code>PARTTIMEJOB = 2;</code>
   */
  public static final int PARTTIMEJOB_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static JobType valueOf(int value) {
    return forNumber(value);
  }

  public static JobType forNumber(int value) {
    switch (value) {
      case 0: return LONG;
      case 1: return SHORT;
      case 2: return PARTTIMEJOB;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JobType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      JobType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JobType>() {
          public JobType findValueByNumber(int number) {
            return JobType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.kptl.proto.job.JobOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final JobType[] VALUES = values();

  public static JobType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JobType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:job.JobType)
}

