// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job/Job.proto

package com.kptl.proto.job;

public interface SaveJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.SaveJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.global.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.global.ResponseHeader header = 1;</code>
   */
  global.Headers.ResponseHeader getHeader();
  /**
   * <code>.global.ResponseHeader header = 1;</code>
   */
  global.Headers.ResponseHeaderOrBuilder getHeaderOrBuilder();
}
