// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto.job;

public interface SaveJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.SaveJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.job.ResponseHeader getHeader();
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.job.ResponseHeaderOrBuilder getHeaderOrBuilder();
}
