// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee/employee.proto

package com.kptl.proto.employee;

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_OperateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_OperateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_FindRecordsReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_FindRecordsReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_SelfInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_SelfInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_SimpleInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_SimpleInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_FindEmployeeInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_FindEmployeeInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_SplitPage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_SplitPage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_FindEmployeeSimpleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_FindEmployeeSimpleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_FindEmployeeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_FindEmployeeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_OperateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_OperateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027employee/employee.proto\022\010employee\032\024glo" +
      "bal/headers.proto\"+\n\016OperateRequest\022\n\n\002i" +
      "d\030\001 \001(\005\022\r\n\005jobId\030\002 \001(\005\"\034\n\016FindRecordsReq" +
      "\022\n\n\002id\030\001 \001(\005\"\234\001\n\017SelfInformation\022/\n\nsimp" +
      "leInfo\030\001 \001(\0132\033.employee.SimpleInformatio" +
      "n\022\017\n\007isMarry\030\002 \001(\005\022\021\n\teducation\030\003 \001(\005\022\021\n" +
      "\tjobStatus\030\004 \001(\005\022\014\n\004home\030\005 \001(\t\022\023\n\013expect" +
      "Money\030\006 \001(\005\"\240\001\n\021SimpleInformation\022\n\n\002id\030" +
      "\001 \001(\005\022\020\n\010realName\030\002 \001(\t\022\013\n\003sex\030\003 \001(\005\022\020\n\010" +
      "workYear\030\004 \001(\005\022\030\n\020expectedLocation\030\005 \001(\t" +
      "\022\020\n\010industry\030\006 \001(\t\022\"\n\007jobType\030\007 \001(\0162\021.em" +
      "ployee.JobType\"!\n\023FindEmployeeInfoReq\022\n\n" +
      "\002id\030\001 \001(\005\"(\n\tSplitPage\022\r\n\005index\030\001 \001(\005\022\014\n" +
      "\004size\030\002 \001(\005\"t\n\032FindEmployeeSimpleRespons" +
      "e\022&\n\006header\030\001 \001(\0132\026.global.ResponseHeade" +
      "r\022.\n\temployees\030\002 \003(\0132\033.employee.SimpleIn" +
      "formation\"k\n\024FindEmployeeResponse\022&\n\006hea" +
      "der\030\001 \001(\0132\026.global.ResponseHeader\022+\n\010sel" +
      "fInfo\030\002 \001(\0132\031.employee.SelfInformation\"I" +
      "\n\017OperateResponse\022&\n\006header\030\001 \001(\0132\026.glob" +
      "al.ResponseHeader\022\016\n\006jobIds\030\002 \003(\005*/\n\007Job" +
      "Type\022\010\n\004LONG\020\000\022\t\n\005SHORT\020\001\022\017\n\013PARTTIMEJOB" +
      "\020\0022\257\004\n\010Employee\022@\n\007deliver\022\030.employee.Op" +
      "erateRequest\032\031.employee.OperateResponse\"" +
      "\000\022@\n\007browses\022\030.employee.OperateRequest\032\031" +
      ".employee.OperateResponse\"\000\022G\n\016deliverRe" +
      "cords\022\030.employee.FindRecordsReq\032\031.employ" +
      "ee.OperateResponse\"\000\022N\n\027completeSelfInfo" +
      "rmation\022\031.employee.SelfInformation\032\026.glo" +
      "bal.ResponseHeader\"\000\022Z\n\027findEmployeeInfo" +
      "rmation\022\035.employee.FindEmployeeInfoReq\032\036" +
      ".employee.FindEmployeeResponse\"\000\022\\\n\035find" +
      "EmployeeSimpleInformation\022\023.employee.Spl" +
      "itPage\032$.employee.FindEmployeeSimpleResp" +
      "onse\"\000\022L\n\025updateSelfInformation\022\031.employ" +
      "ee.SelfInformation\032\026.global.ResponseHead" +
      "er\"\000B\033\n\027com.kptl.proto.employeeP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          global.Headers.getDescriptor(),
        }, assigner);
    internal_static_employee_OperateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employee_OperateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_OperateRequest_descriptor,
        new java.lang.String[] { "Id", "JobId", });
    internal_static_employee_FindRecordsReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_employee_FindRecordsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_FindRecordsReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_employee_SelfInformation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_employee_SelfInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_SelfInformation_descriptor,
        new java.lang.String[] { "SimpleInfo", "IsMarry", "Education", "JobStatus", "Home", "ExpectMoney", });
    internal_static_employee_SimpleInformation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_employee_SimpleInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_SimpleInformation_descriptor,
        new java.lang.String[] { "Id", "RealName", "Sex", "WorkYear", "ExpectedLocation", "Industry", "JobType", });
    internal_static_employee_FindEmployeeInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_employee_FindEmployeeInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_FindEmployeeInfoReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_employee_SplitPage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_employee_SplitPage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_SplitPage_descriptor,
        new java.lang.String[] { "Index", "Size", });
    internal_static_employee_FindEmployeeSimpleResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_employee_FindEmployeeSimpleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_FindEmployeeSimpleResponse_descriptor,
        new java.lang.String[] { "Header", "Employees", });
    internal_static_employee_FindEmployeeResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_employee_FindEmployeeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_FindEmployeeResponse_descriptor,
        new java.lang.String[] { "Header", "SelfInfo", });
    internal_static_employee_OperateResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_employee_OperateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_OperateResponse_descriptor,
        new java.lang.String[] { "Header", "JobIds", });
    global.Headers.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
