// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee/employee.proto

package com.kptl.proto.employee;

public interface FindEmployeeSimpleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employee.FindEmployeeSimpleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.global.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.global.ResponseHeader header = 1;</code>
   */
  global.Headers.ResponseHeader getHeader();
  /**
   * <code>.global.ResponseHeader header = 1;</code>
   */
  global.Headers.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .employee.SimpleInformation employees = 2;</code>
   */
  java.util.List<com.kptl.proto.employee.SimpleInformation> 
      getEmployeesList();
  /**
   * <code>repeated .employee.SimpleInformation employees = 2;</code>
   */
  com.kptl.proto.employee.SimpleInformation getEmployees(int index);
  /**
   * <code>repeated .employee.SimpleInformation employees = 2;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .employee.SimpleInformation employees = 2;</code>
   */
  java.util.List<? extends com.kptl.proto.employee.SimpleInformationOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .employee.SimpleInformation employees = 2;</code>
   */
  com.kptl.proto.employee.SimpleInformationOrBuilder getEmployeesOrBuilder(
      int index);
}
