// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.kptl.proto.employee;

public interface OperateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employee.OperateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.employee.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.employee.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.employee.ResponseHeader getHeader();
  /**
   * <code>.employee.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.employee.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated int32 jobIds = 2;</code>
   */
  java.util.List<java.lang.Integer> getJobIdsList();
  /**
   * <code>repeated int32 jobIds = 2;</code>
   */
  int getJobIdsCount();
  /**
   * <code>repeated int32 jobIds = 2;</code>
   */
  int getJobIds(int index);
}
