// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.CommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.ResponseHeader getHeader();
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.ResponseHeaderOrBuilder getHeaderOrBuilder();
}
