// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface CompanyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.Company)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   *公司名称
   * </pre>
   *
   * <code>string companyName = 2;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <pre>
   *公司名称
   * </pre>
   *
   * <code>string companyName = 2;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <pre>
   *地址
   * </pre>
   *
   * <code>string companyLocation = 3;</code>
   */
  java.lang.String getCompanyLocation();
  /**
   * <pre>
   *地址
   * </pre>
   *
   * <code>string companyLocation = 3;</code>
   */
  com.google.protobuf.ByteString
      getCompanyLocationBytes();

  /**
   * <pre>
   *是否会员
   * </pre>
   *
   * <code>int32 isVip = 4;</code>
   */
  int getIsVip();

  /**
   * <pre>
   *是否认证
   * </pre>
   *
   * <code>int32 isCertified = 5;</code>
   */
  int getIsCertified();

  /**
   * <pre>
   *注册时间
   * </pre>
   *
   * <code>int64 registerTime = 6;</code>
   */
  long getRegisterTime();

  /**
   * <pre>
   *刷新时间
   * </pre>
   *
   * <code>int64 updateTime = 7;</code>
   */
  long getUpdateTime();

  /**
   * <pre>
   *行业
   * </pre>
   *
   * <code>string industry = 8;</code>
   */
  java.lang.String getIndustry();
  /**
   * <pre>
   *行业
   * </pre>
   *
   * <code>string industry = 8;</code>
   */
  com.google.protobuf.ByteString
      getIndustryBytes();

  /**
   * <pre>
   *公司id
   * </pre>
   *
   * <code>int32 companyId = 9;</code>
   */
  int getCompanyId();
}
