// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface FindJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 role = 2;</code>
   */
  int getRole();

  /**
   * <code>int32 byId = 3;</code>
   */
  int getById();
}
