// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface FindJobByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 jobId = 1;</code>
   */
  int getJobId();
}
