// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface FindJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.ResponseHeader getHeader();
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>.job.JobMessage jobMsg = 2;</code>
   */
  boolean hasJobMsg();
  /**
   * <code>.job.JobMessage jobMsg = 2;</code>
   */
  com.kptl.proto.JobMessage getJobMsg();
  /**
   * <code>.job.JobMessage jobMsg = 2;</code>
   */
  com.kptl.proto.JobMessageOrBuilder getJobMsgOrBuilder();
}
