// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

/**
 * Protobuf type {@code job.FindJobResponse}
 */
public  final class FindJobResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:job.FindJobResponse)
    FindJobResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindJobResponse.newBuilder() to construct.
  private FindJobResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindJobResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FindJobResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.kptl.proto.ResponseHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(com.kptl.proto.ResponseHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.kptl.proto.JobMessage.Builder subBuilder = null;
            if (jobMsg_ != null) {
              subBuilder = jobMsg_.toBuilder();
            }
            jobMsg_ = input.readMessage(com.kptl.proto.JobMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(jobMsg_);
              jobMsg_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kptl.proto.JobOuterClass.internal_static_job_FindJobResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kptl.proto.JobOuterClass.internal_static_job_FindJobResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kptl.proto.FindJobResponse.class, com.kptl.proto.FindJobResponse.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private com.kptl.proto.ResponseHeader header_;
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  public com.kptl.proto.ResponseHeader getHeader() {
    return header_ == null ? com.kptl.proto.ResponseHeader.getDefaultInstance() : header_;
  }
  /**
   * <code>.job.ResponseHeader header = 1;</code>
   */
  public com.kptl.proto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int JOBMSG_FIELD_NUMBER = 2;
  private com.kptl.proto.JobMessage jobMsg_;
  /**
   * <code>.job.JobMessage jobMsg = 2;</code>
   */
  public boolean hasJobMsg() {
    return jobMsg_ != null;
  }
  /**
   * <code>.job.JobMessage jobMsg = 2;</code>
   */
  public com.kptl.proto.JobMessage getJobMsg() {
    return jobMsg_ == null ? com.kptl.proto.JobMessage.getDefaultInstance() : jobMsg_;
  }
  /**
   * <code>.job.JobMessage jobMsg = 2;</code>
   */
  public com.kptl.proto.JobMessageOrBuilder getJobMsgOrBuilder() {
    return getJobMsg();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (jobMsg_ != null) {
      output.writeMessage(2, getJobMsg());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (jobMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getJobMsg());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kptl.proto.FindJobResponse)) {
      return super.equals(obj);
    }
    com.kptl.proto.FindJobResponse other = (com.kptl.proto.FindJobResponse) obj;

    boolean result = true;
    result = result && (hasHeader() == other.hasHeader());
    if (hasHeader()) {
      result = result && getHeader()
          .equals(other.getHeader());
    }
    result = result && (hasJobMsg() == other.hasJobMsg());
    if (hasJobMsg()) {
      result = result && getJobMsg()
          .equals(other.getJobMsg());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    if (hasJobMsg()) {
      hash = (37 * hash) + JOBMSG_FIELD_NUMBER;
      hash = (53 * hash) + getJobMsg().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kptl.proto.FindJobResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kptl.proto.FindJobResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kptl.proto.FindJobResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kptl.proto.FindJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kptl.proto.FindJobResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code job.FindJobResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:job.FindJobResponse)
      com.kptl.proto.FindJobResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kptl.proto.JobOuterClass.internal_static_job_FindJobResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kptl.proto.JobOuterClass.internal_static_job_FindJobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kptl.proto.FindJobResponse.class, com.kptl.proto.FindJobResponse.Builder.class);
    }

    // Construct using com.kptl.proto.FindJobResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      if (jobMsgBuilder_ == null) {
        jobMsg_ = null;
      } else {
        jobMsg_ = null;
        jobMsgBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kptl.proto.JobOuterClass.internal_static_job_FindJobResponse_descriptor;
    }

    public com.kptl.proto.FindJobResponse getDefaultInstanceForType() {
      return com.kptl.proto.FindJobResponse.getDefaultInstance();
    }

    public com.kptl.proto.FindJobResponse build() {
      com.kptl.proto.FindJobResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.kptl.proto.FindJobResponse buildPartial() {
      com.kptl.proto.FindJobResponse result = new com.kptl.proto.FindJobResponse(this);
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      if (jobMsgBuilder_ == null) {
        result.jobMsg_ = jobMsg_;
      } else {
        result.jobMsg_ = jobMsgBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kptl.proto.FindJobResponse) {
        return mergeFrom((com.kptl.proto.FindJobResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kptl.proto.FindJobResponse other) {
      if (other == com.kptl.proto.FindJobResponse.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (other.hasJobMsg()) {
        mergeJobMsg(other.getJobMsg());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kptl.proto.FindJobResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kptl.proto.FindJobResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.kptl.proto.ResponseHeader header_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kptl.proto.ResponseHeader, com.kptl.proto.ResponseHeader.Builder, com.kptl.proto.ResponseHeaderOrBuilder> headerBuilder_;
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    public com.kptl.proto.ResponseHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.kptl.proto.ResponseHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    public Builder setHeader(com.kptl.proto.ResponseHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    public Builder setHeader(
        com.kptl.proto.ResponseHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    public Builder mergeHeader(com.kptl.proto.ResponseHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            com.kptl.proto.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    public com.kptl.proto.ResponseHeader.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    public com.kptl.proto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.kptl.proto.ResponseHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <code>.job.ResponseHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kptl.proto.ResponseHeader, com.kptl.proto.ResponseHeader.Builder, com.kptl.proto.ResponseHeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.kptl.proto.ResponseHeader, com.kptl.proto.ResponseHeader.Builder, com.kptl.proto.ResponseHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private com.kptl.proto.JobMessage jobMsg_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kptl.proto.JobMessage, com.kptl.proto.JobMessage.Builder, com.kptl.proto.JobMessageOrBuilder> jobMsgBuilder_;
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    public boolean hasJobMsg() {
      return jobMsgBuilder_ != null || jobMsg_ != null;
    }
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    public com.kptl.proto.JobMessage getJobMsg() {
      if (jobMsgBuilder_ == null) {
        return jobMsg_ == null ? com.kptl.proto.JobMessage.getDefaultInstance() : jobMsg_;
      } else {
        return jobMsgBuilder_.getMessage();
      }
    }
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    public Builder setJobMsg(com.kptl.proto.JobMessage value) {
      if (jobMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        jobMsg_ = value;
        onChanged();
      } else {
        jobMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    public Builder setJobMsg(
        com.kptl.proto.JobMessage.Builder builderForValue) {
      if (jobMsgBuilder_ == null) {
        jobMsg_ = builderForValue.build();
        onChanged();
      } else {
        jobMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    public Builder mergeJobMsg(com.kptl.proto.JobMessage value) {
      if (jobMsgBuilder_ == null) {
        if (jobMsg_ != null) {
          jobMsg_ =
            com.kptl.proto.JobMessage.newBuilder(jobMsg_).mergeFrom(value).buildPartial();
        } else {
          jobMsg_ = value;
        }
        onChanged();
      } else {
        jobMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    public Builder clearJobMsg() {
      if (jobMsgBuilder_ == null) {
        jobMsg_ = null;
        onChanged();
      } else {
        jobMsg_ = null;
        jobMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    public com.kptl.proto.JobMessage.Builder getJobMsgBuilder() {
      
      onChanged();
      return getJobMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    public com.kptl.proto.JobMessageOrBuilder getJobMsgOrBuilder() {
      if (jobMsgBuilder_ != null) {
        return jobMsgBuilder_.getMessageOrBuilder();
      } else {
        return jobMsg_ == null ?
            com.kptl.proto.JobMessage.getDefaultInstance() : jobMsg_;
      }
    }
    /**
     * <code>.job.JobMessage jobMsg = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kptl.proto.JobMessage, com.kptl.proto.JobMessage.Builder, com.kptl.proto.JobMessageOrBuilder> 
        getJobMsgFieldBuilder() {
      if (jobMsgBuilder_ == null) {
        jobMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.kptl.proto.JobMessage, com.kptl.proto.JobMessage.Builder, com.kptl.proto.JobMessageOrBuilder>(
                getJobMsg(),
                getParentForChildren(),
                isClean());
        jobMsg_ = null;
      }
      return jobMsgBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:job.FindJobResponse)
  }

  // @@protoc_insertion_point(class_scope:job.FindJobResponse)
  private static final com.kptl.proto.FindJobResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kptl.proto.FindJobResponse();
  }

  public static com.kptl.proto.FindJobResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindJobResponse>
      PARSER = new com.google.protobuf.AbstractParser<FindJobResponse>() {
    public FindJobResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FindJobResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FindJobResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FindJobResponse> getParserForType() {
    return PARSER;
  }

  public com.kptl.proto.FindJobResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

