// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface FindJobByNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobByNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jobName = 1;</code>
   */
  java.lang.String getJobName();
  /**
   * <code>string jobName = 1;</code>
   */
  com.google.protobuf.ByteString
      getJobNameBytes();
}
