// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface FindAllCompaniesReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindAllCompaniesReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   */
  int getIndex();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();
}
