// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface FindJobByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.FindJobByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jobId = 1;</code>
   */
  java.lang.String getJobId();
  /**
   * <code>string jobId = 1;</code>
   */
  com.google.protobuf.ByteString
      getJobIdBytes();
}
