// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public final class Job {
  private Job() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_job_FindJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_job_FindJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_job_FindJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_job_FindJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_job_SaveJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_job_SaveJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_job_ResponseHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_job_ResponseHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_job_JobMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_job_JobMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tJob.proto\022\003job\"8\n\016FindJobRequest\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004role\030\002 \001(\005\022\014\n\004byId\030\003 \001(\005\"W\n\017Fi" +
      "ndJobResponse\022#\n\006header\030\001 \001(\0132\023.job.Resp" +
      "onseHeader\022\037\n\006jobMsg\030\002 \001(\0132\017.job.JobMess" +
      "age\"6\n\017SaveJobResponse\022#\n\006header\030\001 \001(\0132\023" +
      ".job.ResponseHeader\"F\n\016ResponseHeader\022#\n" +
      "\006status\030\001 \001(\0162\023.job.ResponseStatus\022\017\n\007me" +
      "ssage\030\002 \001(\t\"\202\002\n\nJobMessage\022\r\n\005jobId\030\002 \001(" +
      "\005\022\017\n\007jobName\030\003 \001(\t\022\020\n\010jobMoney\030\004 \001(\005\022\016\n\006" +
      "jobReq\030\005 \001(\t\022\023\n\013jobLocation\030\006 \001(\t\022\021\n\tcom" +
      "panyId\030\007 \001(\005\022\025\n\rrecruiterName\030\010 \001(\t\022\026\n\016r" +
      "ecruiterPhone\030\t \001(\t\022\017\n\007jobNeed\030\n \001(\005\022\023\n\013" +
      "recruiterId\030\013 \001(\005\022\020\n\010openTime\030\014 \001(\003\022\017\n\007j" +
      "obTags\030\r \001(\t\022\022\n\nupdateTime\030\016 \001(\003*)\n\016Resp" +
      "onseStatus\022\006\n\002OK\020\000\022\017\n\013InternalErr\020\0012\257\001\n\010" +
      "Employee\0227\n\010FindJobs\022\023.job.FindJobReques" +
      "t\032\024.job.FindJobResponse\"\000\0223\n\010SaveJobs\022\017." +
      "job.JobMessage\032\024.job.SaveJobResponse\"\000\0225" +
      "\n\nUpdateJobs\022\017.job.JobMessage\032\024.job.Save" +
      "JobResponse\"\000B\022\n\016com.kptl.protoP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_job_FindJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_job_FindJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_job_FindJobRequest_descriptor,
        new java.lang.String[] { "Id", "Role", "ById", });
    internal_static_job_FindJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_job_FindJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_job_FindJobResponse_descriptor,
        new java.lang.String[] { "Header", "JobMsg", });
    internal_static_job_SaveJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_job_SaveJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_job_SaveJobResponse_descriptor,
        new java.lang.String[] { "Header", });
    internal_static_job_ResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_job_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_job_ResponseHeader_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_job_JobMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_job_JobMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_job_JobMessage_descriptor,
        new java.lang.String[] { "JobId", "JobName", "JobMoney", "JobReq", "JobLocation", "CompanyId", "RecruiterName", "RecruiterPhone", "JobNeed", "RecruiterId", "OpenTime", "JobTags", "UpdateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
