// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface JobMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.JobMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.job.JobSimplifyMessage jobBaseMsg = 1;</code>
   */
  boolean hasJobBaseMsg();
  /**
   * <code>.job.JobSimplifyMessage jobBaseMsg = 1;</code>
   */
  com.kptl.proto.JobSimplifyMessage getJobBaseMsg();
  /**
   * <code>.job.JobSimplifyMessage jobBaseMsg = 1;</code>
   */
  com.kptl.proto.JobSimplifyMessageOrBuilder getJobBaseMsgOrBuilder();

  /**
   * <pre>
   *职位要求
   * </pre>
   *
   * <code>string jobReq = 2;</code>
   */
  java.lang.String getJobReq();
  /**
   * <pre>
   *职位要求
   * </pre>
   *
   * <code>string jobReq = 2;</code>
   */
  com.google.protobuf.ByteString
      getJobReqBytes();

  /**
   * <pre>
   *招聘人数
   * </pre>
   *
   * <code>int32 jobNeed = 3;</code>
   */
  int getJobNeed();

  /**
   * <pre>
   *行业
   * </pre>
   *
   * <code>string industry = 5;</code>
   */
  java.lang.String getIndustry();
  /**
   * <pre>
   *行业
   * </pre>
   *
   * <code>string industry = 5;</code>
   */
  com.google.protobuf.ByteString
      getIndustryBytes();

  /**
   * <pre>
   *招聘者
   * </pre>
   *
   * <code>string recruiterName = 6;</code>
   */
  java.lang.String getRecruiterName();
  /**
   * <pre>
   *招聘者
   * </pre>
   *
   * <code>string recruiterName = 6;</code>
   */
  com.google.protobuf.ByteString
      getRecruiterNameBytes();

  /**
   * <pre>
   *招聘者手机号
   * </pre>
   *
   * <code>string recruiterPhone = 7;</code>
   */
  java.lang.String getRecruiterPhone();
  /**
   * <pre>
   *招聘者手机号
   * </pre>
   *
   * <code>string recruiterPhone = 7;</code>
   */
  com.google.protobuf.ByteString
      getRecruiterPhoneBytes();

  /**
   * <pre>
   *招聘者id
   * </pre>
   *
   * <code>int32 recruiterId = 8;</code>
   */
  int getRecruiterId();

  /**
   * <pre>
   *职位刷新时间
   * </pre>
   *
   * <code>int64 updateTime = 9;</code>
   */
  long getUpdateTime();
}
