// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface JobSimplifyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.JobSimplifyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 jobId = 1;</code>
   */
  int getJobId();

  /**
   * <pre>
   *职位名称
   * </pre>
   *
   * <code>string jobName = 2;</code>
   */
  java.lang.String getJobName();
  /**
   * <pre>
   *职位名称
   * </pre>
   *
   * <code>string jobName = 2;</code>
   */
  com.google.protobuf.ByteString
      getJobNameBytes();

  /**
   * <pre>
   *职位地址
   * </pre>
   *
   * <code>string jobLocation = 3;</code>
   */
  java.lang.String getJobLocation();
  /**
   * <pre>
   *职位地址
   * </pre>
   *
   * <code>string jobLocation = 3;</code>
   */
  com.google.protobuf.ByteString
      getJobLocationBytes();

  /**
   * <code>string companyName = 4;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 4;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <pre>
   *职位标签
   * </pre>
   *
   * <code>string jobTags = 5;</code>
   */
  java.lang.String getJobTags();
  /**
   * <pre>
   *职位标签
   * </pre>
   *
   * <code>string jobTags = 5;</code>
   */
  com.google.protobuf.ByteString
      getJobTagsBytes();

  /**
   * <code>int32 companyId = 6;</code>
   */
  int getCompanyId();

  /**
   * <pre>
   *职位发布时间
   * </pre>
   *
   * <code>int64 openTime = 7;</code>
   */
  long getOpenTime();

  /**
   * <code>.job.JobMoney jobMoney = 8;</code>
   */
  boolean hasJobMoney();
  /**
   * <code>.job.JobMoney jobMoney = 8;</code>
   */
  com.kptl.proto.JobMoney getJobMoney();
  /**
   * <code>.job.JobMoney jobMoney = 8;</code>
   */
  com.kptl.proto.JobMoneyOrBuilder getJobMoneyOrBuilder();

  /**
   * <code>.job.JobType jobType = 9;</code>
   */
  int getJobTypeValue();
  /**
   * <code>.job.JobType jobType = 9;</code>
   */
  com.kptl.proto.JobType getJobType();
}
