// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface RegisteredCompanyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.RegisteredCompanyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.job.Company company = 1;</code>
   */
  boolean hasCompany();
  /**
   * <code>.job.Company company = 1;</code>
   */
  com.kptl.proto.Company getCompany();
  /**
   * <code>.job.Company company = 1;</code>
   */
  com.kptl.proto.CompanyOrBuilder getCompanyOrBuilder();
}
