// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.kptl.proto;

public interface RegisteredRecruiterReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:job.RegisteredRecruiterReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
