// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee/Employee.proto

package com.kptl.proto;

/**
 * Protobuf type {@code employee.OperateResponse}
 */
public  final class OperateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employee.OperateResponse)
    OperateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OperateResponse.newBuilder() to construct.
  private OperateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OperateResponse() {
    jobIds_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OperateResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.kptl.proto.ResponseHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(com.kptl.proto.ResponseHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              jobIds_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            jobIds_.add(input.readInt32());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              jobIds_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              jobIds_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        jobIds_ = java.util.Collections.unmodifiableList(jobIds_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kptl.proto.EmployeeOuterClass.internal_static_employee_OperateResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kptl.proto.EmployeeOuterClass.internal_static_employee_OperateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kptl.proto.OperateResponse.class, com.kptl.proto.OperateResponse.Builder.class);
  }

  private int bitField0_;
  public static final int HEADER_FIELD_NUMBER = 1;
  private com.kptl.proto.ResponseHeader header_;
  /**
   * <code>.employee.ResponseHeader header = 1;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <code>.employee.ResponseHeader header = 1;</code>
   */
  public com.kptl.proto.ResponseHeader getHeader() {
    return header_ == null ? com.kptl.proto.ResponseHeader.getDefaultInstance() : header_;
  }
  /**
   * <code>.employee.ResponseHeader header = 1;</code>
   */
  public com.kptl.proto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int JOBIDS_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> jobIds_;
  /**
   * <code>repeated int32 jobIds = 2;</code>
   */
  public java.util.List<java.lang.Integer>
      getJobIdsList() {
    return jobIds_;
  }
  /**
   * <code>repeated int32 jobIds = 2;</code>
   */
  public int getJobIdsCount() {
    return jobIds_.size();
  }
  /**
   * <code>repeated int32 jobIds = 2;</code>
   */
  public int getJobIds(int index) {
    return jobIds_.get(index);
  }
  private int jobIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (getJobIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(jobIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < jobIds_.size(); i++) {
      output.writeInt32NoTag(jobIds_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < jobIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(jobIds_.get(i));
      }
      size += dataSize;
      if (!getJobIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      jobIdsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kptl.proto.OperateResponse)) {
      return super.equals(obj);
    }
    com.kptl.proto.OperateResponse other = (com.kptl.proto.OperateResponse) obj;

    boolean result = true;
    result = result && (hasHeader() == other.hasHeader());
    if (hasHeader()) {
      result = result && getHeader()
          .equals(other.getHeader());
    }
    result = result && getJobIdsList()
        .equals(other.getJobIdsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    if (getJobIdsCount() > 0) {
      hash = (37 * hash) + JOBIDS_FIELD_NUMBER;
      hash = (53 * hash) + getJobIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kptl.proto.OperateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.OperateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.OperateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.OperateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.OperateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kptl.proto.OperateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kptl.proto.OperateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kptl.proto.OperateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kptl.proto.OperateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kptl.proto.OperateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kptl.proto.OperateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kptl.proto.OperateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kptl.proto.OperateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employee.OperateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employee.OperateResponse)
      com.kptl.proto.OperateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kptl.proto.EmployeeOuterClass.internal_static_employee_OperateResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kptl.proto.EmployeeOuterClass.internal_static_employee_OperateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kptl.proto.OperateResponse.class, com.kptl.proto.OperateResponse.Builder.class);
    }

    // Construct using com.kptl.proto.OperateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      jobIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kptl.proto.EmployeeOuterClass.internal_static_employee_OperateResponse_descriptor;
    }

    public com.kptl.proto.OperateResponse getDefaultInstanceForType() {
      return com.kptl.proto.OperateResponse.getDefaultInstance();
    }

    public com.kptl.proto.OperateResponse build() {
      com.kptl.proto.OperateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.kptl.proto.OperateResponse buildPartial() {
      com.kptl.proto.OperateResponse result = new com.kptl.proto.OperateResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        jobIds_ = java.util.Collections.unmodifiableList(jobIds_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.jobIds_ = jobIds_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kptl.proto.OperateResponse) {
        return mergeFrom((com.kptl.proto.OperateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kptl.proto.OperateResponse other) {
      if (other == com.kptl.proto.OperateResponse.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.jobIds_.isEmpty()) {
        if (jobIds_.isEmpty()) {
          jobIds_ = other.jobIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureJobIdsIsMutable();
          jobIds_.addAll(other.jobIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kptl.proto.OperateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kptl.proto.OperateResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.kptl.proto.ResponseHeader header_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kptl.proto.ResponseHeader, com.kptl.proto.ResponseHeader.Builder, com.kptl.proto.ResponseHeaderOrBuilder> headerBuilder_;
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    public com.kptl.proto.ResponseHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.kptl.proto.ResponseHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    public Builder setHeader(com.kptl.proto.ResponseHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    public Builder setHeader(
        com.kptl.proto.ResponseHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    public Builder mergeHeader(com.kptl.proto.ResponseHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            com.kptl.proto.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    public com.kptl.proto.ResponseHeader.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    public com.kptl.proto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.kptl.proto.ResponseHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <code>.employee.ResponseHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kptl.proto.ResponseHeader, com.kptl.proto.ResponseHeader.Builder, com.kptl.proto.ResponseHeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.kptl.proto.ResponseHeader, com.kptl.proto.ResponseHeader.Builder, com.kptl.proto.ResponseHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.util.List<java.lang.Integer> jobIds_ = java.util.Collections.emptyList();
    private void ensureJobIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        jobIds_ = new java.util.ArrayList<java.lang.Integer>(jobIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int32 jobIds = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getJobIdsList() {
      return java.util.Collections.unmodifiableList(jobIds_);
    }
    /**
     * <code>repeated int32 jobIds = 2;</code>
     */
    public int getJobIdsCount() {
      return jobIds_.size();
    }
    /**
     * <code>repeated int32 jobIds = 2;</code>
     */
    public int getJobIds(int index) {
      return jobIds_.get(index);
    }
    /**
     * <code>repeated int32 jobIds = 2;</code>
     */
    public Builder setJobIds(
        int index, int value) {
      ensureJobIdsIsMutable();
      jobIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 jobIds = 2;</code>
     */
    public Builder addJobIds(int value) {
      ensureJobIdsIsMutable();
      jobIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 jobIds = 2;</code>
     */
    public Builder addAllJobIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureJobIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, jobIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 jobIds = 2;</code>
     */
    public Builder clearJobIds() {
      jobIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employee.OperateResponse)
  }

  // @@protoc_insertion_point(class_scope:employee.OperateResponse)
  private static final com.kptl.proto.OperateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kptl.proto.OperateResponse();
  }

  public static com.kptl.proto.OperateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OperateResponse>
      PARSER = new com.google.protobuf.AbstractParser<OperateResponse>() {
    public OperateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OperateResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OperateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OperateResponse> getParserForType() {
    return PARSER;
  }

  public com.kptl.proto.OperateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

