// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

package com.kptl.proto.company;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:company.CommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.company.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.company.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.company.ResponseHeader getHeader();
  /**
   * <code>.company.ResponseHeader header = 1;</code>
   */
  com.kptl.proto.company.ResponseHeaderOrBuilder getHeaderOrBuilder();
}
