// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

package com.kptl.proto.company;

public final class CompanyOuterClass {
  private CompanyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_ResponseHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_ResponseHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_RegisteredCompanyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_RegisteredCompanyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_Company_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_Company_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_CommonCompanyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_CommonCompanyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_CommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_CommonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_FindCompanyByNameReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_FindCompanyByNameReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_FindAllCompaniesReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_FindAllCompaniesReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_CommonCompanyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_CommonCompanyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_FindCompanyByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_FindCompanyByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_FindCompanyByIndustryReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_FindCompanyByIndustryReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcompany.proto\022\007company\"J\n\016ResponseHead" +
      "er\022\'\n\006status\030\001 \001(\0162\027.company.ResponseSta" +
      "tus\022\017\n\007message\030\002 \001(\t\"9\n\024RegisteredCompan" +
      "yReq\022!\n\007company\030\001 \001(\0132\020.company.Company\"" +
      "\266\001\n\007Company\022\n\n\002id\030\001 \001(\005\022\023\n\013companyName\030\002" +
      " \001(\t\022\027\n\017companyLocation\030\003 \001(\t\022\r\n\005isVip\030\004" +
      " \001(\005\022\023\n\013isCertified\030\005 \001(\005\022\024\n\014registerTim" +
      "e\030\006 \001(\003\022\022\n\nupdateTime\030\007 \001(\003\022\020\n\010industry\030" +
      "\010 \001(\t\022\021\n\tcompanyId\030\t \001(\005\"\036\n\020CommonCompan" +
      "yReq\022\n\n\002id\030\001 \001(\005\"9\n\016CommonResponse\022\'\n\006he" +
      "ader\030\001 \001(\0132\027.company.ResponseHeader\"A\n\024F" +
      "indCompanyByNameReq\022\014\n\004name\030\001 \001(\t\022\r\n\005ind" +
      "ex\030\002 \001(\005\022\014\n\004size\030\003 \001(\005\"2\n\023FindAllCompani" +
      "esReq\022\r\n\005index\030\001 \001(\005\022\014\n\004size\030\002 \001(\005\"e\n\025Co" +
      "mmonCompanyResponse\022\'\n\006header\030\001 \001(\0132\027.co" +
      "mpany.ResponseHeader\022#\n\tcompanies\030\002 \003(\0132" +
      "\020.company.Company\"e\n\027FindCompanyByIdResp" +
      "onse\022\'\n\006header\030\001 \001(\0132\027.company.ResponseH" +
      "eader\022!\n\007company\030\002 \001(\0132\020.company.Company" +
      "\"I\n\030FindCompanyByIndustryReq\022\020\n\010industry" +
      "\030\001 \001(\t\022\r\n\005index\030\002 \001(\005\022\014\n\004size\030\003 \001(\005*)\n\016R" +
      "esponseStatus\022\006\n\002OK\020\000\022\017\n\013InternalErr\020\0012\204" +
      "\005\n\016CompanyService\022@\n\021registeredCompany\022\020" +
      ".company.Company\032\027.company.CommonRespons" +
      "e\"\000\022I\n\rupdateCompany\022\035.company.Registere" +
      "dCompanyReq\032\027.company.CommonResponse\"\000\022T" +
      "\n\021findCompanyByName\022\035.company.FindCompan" +
      "yByNameReq\032\036.company.CommonCompanyRespon" +
      "se\"\000\022P\n\017findCompanyById\022\031.company.Common" +
      "CompanyReq\032 .company.FindCompanyByIdResp" +
      "onse\"\000\022R\n\020findAllCompanies\022\034.company.Fin" +
      "dAllCompaniesReq\032\036.company.CommonCompany" +
      "Response\"\000\022D\n\014boundCompany\022\031.company.Com" +
      "monCompanyReq\032\027.company.CommonResponse\"\000" +
      "\022E\n\rverifyCompany\022\031.company.CommonCompan" +
      "yReq\032\027.company.CommonResponse\"\000\022\\\n\025findC" +
      "ompanyByIndustry\022!.company.FindCompanyBy" +
      "IndustryReq\032\036.company.CommonCompanyRespo" +
      "nse\"\000B%\n\026com.kptl.proto.companyP\001Z\t./com" +
      "panyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_company_ResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_company_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_ResponseHeader_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_company_RegisteredCompanyReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_company_RegisteredCompanyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_RegisteredCompanyReq_descriptor,
        new java.lang.String[] { "Company", });
    internal_static_company_Company_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_company_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_Company_descriptor,
        new java.lang.String[] { "Id", "CompanyName", "CompanyLocation", "IsVip", "IsCertified", "RegisterTime", "UpdateTime", "Industry", "CompanyId", });
    internal_static_company_CommonCompanyReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_company_CommonCompanyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_CommonCompanyReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_company_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_company_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_CommonResponse_descriptor,
        new java.lang.String[] { "Header", });
    internal_static_company_FindCompanyByNameReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_company_FindCompanyByNameReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_FindCompanyByNameReq_descriptor,
        new java.lang.String[] { "Name", "Index", "Size", });
    internal_static_company_FindAllCompaniesReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_company_FindAllCompaniesReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_FindAllCompaniesReq_descriptor,
        new java.lang.String[] { "Index", "Size", });
    internal_static_company_CommonCompanyResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_company_CommonCompanyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_CommonCompanyResponse_descriptor,
        new java.lang.String[] { "Header", "Companies", });
    internal_static_company_FindCompanyByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_company_FindCompanyByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_FindCompanyByIdResponse_descriptor,
        new java.lang.String[] { "Header", "Company", });
    internal_static_company_FindCompanyByIndustryReq_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_company_FindCompanyByIndustryReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_FindCompanyByIndustryReq_descriptor,
        new java.lang.String[] { "Industry", "Index", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
