// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

package com.kptl.proto.company;

public interface FindCompanyByIndustryReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:company.FindCompanyByIndustryReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string industry = 1;</code>
   */
  java.lang.String getIndustry();
  /**
   * <code>string industry = 1;</code>
   */
  com.google.protobuf.ByteString
      getIndustryBytes();

  /**
   * <code>int32 index = 2;</code>
   */
  int getIndex();

  /**
   * <code>int32 size = 3;</code>
   */
  int getSize();
}
