// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company/company.proto

package com.kptl.proto.company;

public interface FindCompanyByNameReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:company.FindCompanyByNameReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 index = 2;</code>
   */
  int getIndex();

  /**
   * <code>int32 size = 3;</code>
   */
  int getSize();
}
