// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

package com.kptl.proto.company;

public interface RegisteredCompanyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:company.RegisteredCompanyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.company.Company company = 1;</code>
   */
  boolean hasCompany();
  /**
   * <code>.company.Company company = 1;</code>
   */
  com.kptl.proto.company.Company getCompany();
  /**
   * <code>.company.Company company = 1;</code>
   */
  com.kptl.proto.company.CompanyOrBuilder getCompanyOrBuilder();
}
